### ISSUE TITLE
Zero dollar line items are now getting sent to Gateway if price is a float as 0.0 !== 0

### ISSUE THREAD

**Issue by mambose** [craftcms/commerce-omnipay#24]
Zero dollar line items are now getting sent to the Gateway if the price is converted to a float as 0.0 !== 0.

https://github.com/craftcms/commerce-omnipay/blob/2aa8672fd0c9d096258faf7c41e0514b15d08832/src/base/Gateway.php#L687

This may be due to this recent commit in Craft Commerce https://github.com/craftcms/commerce/commit/2a14968dae26a6167775142fc5473f92b0e6aeef

**Comment by nfourtythree** [comment]
Hi @mambose & @timeverts 

Thank you for reporting this. We have just pushed an update that fixes this issue.

Running `composer update` should get you the latest version of this package.

Thanks.
