### ISSUE TITLE
Update to Omnipay 3.x

### ISSUE THREAD

**Issue by pieterbeulque** [craftcms/commerce-omnipay#3]
Hi, do you have any plans to upgrade to Omnipay 3.x? Can I help in any way?

**Comment by andris-sevcenko** [comment]
It's on the list. The hardest thing about this is that every gateway that uses omnipay has to be updated and tested as well, which creates quite a bit of work for us.

**Comment by boboldehampsink** [comment]
You can test Omnipay 3 by using #7. An example on how to test this can be found at https://github.com/craftcms/commerce-mollie/pull/12

**Comment by andris-sevcenko** [comment]
@pieterbeulque sorry for the delay. The effort to update to Omnipay 3.x is underway.
